services:
  mysql:
    image: mysql:8.0
    container_name: tienda-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: .
    container_name: tienda-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      AWS_S3_REGION: ${AWS_REGION}
      AWS_S3_BUCKETNAME: ${AWS_BUCKET_NAME}
      AWS_S3_ACCESSKEY: ${AWS_ACCESS_KEY}
      AWS_S3_SECRETKEY: ${AWS_SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    depends_on:
      - mysql

  frontend:
    build: ./client
    container_name: tienda-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql-data:
